### ISSUE TITLE
theme-preview fails when sourcing preset

### ISSUE THREAD

**Issue by nojhan** [liquidprompt/liquidprompt#800]
The `theme-preview.sh` script works well for raw themes, but adding presets to the list of sourced files fails on unbound variables and functions. This does not depends on the order of sourced files.

Shell: Bash 5.1.16(1)-release
Operating system: Linux 6.1.0-1008-oem #8-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar  3 10:51:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Liquid Prompt version: dce7453

### Steps to Reproduce

Run `./tools/theme-preview.sh <mytheme> <path/to/mytheme.theme> <any/preset>`

### Expected Behavior

It should possible to combine themes and presets.

### Current Behavior

Examples:
1. `./tools/theme-preview.sh default liquidprompt contrib/presets/more-unicode.conf` => "contrib/presets/more-unicode.conf: line 43: BLUE: unbound variable"
2. `./tools/theme-preview.sh default contrib/presets/more-unicode.conf` => same
3. `./tools/theme-preview.sh default contrib/presets/more-unicode.conf liquidprompt` => same
4. `./tools/theme-preview.sh unfold themes/unfold/unfold.theme contrib/presets/colors/256-colors-dark.conf` => "./liquidprompt: line 1103: LP_ENABLE_COLOR: unbound variable"
5. `./tools/theme-preview.sh default liquidprompt contrib/presets/colors/green-not-blue.conf` => "contrib/presets/colors/green-not-blue.conf: line 3: __lp_foreground_color: command not found
contrib/presets/colors/green-not-blue.conf: line 4: af_color: unbound variable"

**Comment by Rycieos** [comment]
If your "presets" only set variables, they would work. But they reference variables and functions that are only exposed if they are loaded as config files. This works when used in normal Liquid Prompt operation as config files, but here they are being sourced directly.

As an aside, `contrib/presets/colors/green-not-blue.conf` referencing `__lp_foreground_color()` on line 3 isn't a great practice, since it is a private function. Ideally it would use `lp_terminal_format()` instead.

Anyway, I think you have a valid use case here. I am picturing adding these flags to `theme-preview.sh`:
* `--config-file`: Load the following argument as a config file. Can be specified multiple times.
* `--no-config`: Do not load any config files. Useful for a user who wants to see a prompt without their personal config, or for developers to get theme example screenshots.

Both would require changes to `liquidprompt` as well.

Thoughts?

**Comment by nojhan** [comment]
This is a good idea, cleanly separating the loaded config and the one used for screenshots would be a real plus.
