### ISSUE TITLE
Prompt in unprivileged lxc container doesnt show hostname

### ISSUE THREAD

**Issue by Mudla** [liquidprompt/liquidprompt#804]
I'm using liquidprompt in combination with oh-my-zsh a few years now in serveral containers on my server (Proxmox)
A few weeks ago (can't remeber exactly how long)  i wondered on a new container, that there is no hostname in the prompt (default prompt with oh-my-zsh theme "robbyrussel").
After digging a log i found that the main script "liquidprompt" thinks that i'm working local on this container.
In fact i'm using a ssh to my server and enter the container with pct enter xxx.

After commenting out line 2318 (procedure _lp_hostname, where it exits the procedure whene it thinks it's local), hostname will be shown again in prompt.

Shell: zsh 5.9
Operating system: Linux xxx 6.2.16-19-pve #1 SMP PREEMPT_DYNAMIC PMX 6.2.16-19 (2023-10-24T12:07Z) x86_64 GNU/Linux
Liquid Prompt version: 
- 1f7858af421e0c8c45134b509b774842c08d17de (git rev-parse HEAD)
- [2.2.0-rc.1] - 2023-10-23 (from CHANGELOG.md)

**Comment by Rycieos** [comment]
This is (somewhat) expected. The detection of an SSH connection is done by reading environment variables (specifically `SSH_CLIENT`, `SSH2_CLIENT`, and `SSH_TTY`). There is no way to detect an SSH connection other than this. Well, we could check the process tree and see if `ssh` is some parent of the shell, but that would not work inside a container like this since the ssh process is in a different namespace.

So without any of those environment variables in existence, there is nothing `liquidprompt` can do to detect that the parent shell is inside an SSH tunnel.

That said, here are some options you have:
1. Set `SSH_CLIENT` at container creation. Checking `man pct(1)` though, I don't see that as a possibility.
2. Set `SSH_CLIENT` at enter time. I also do not see that in the man page, but you could do this manually with `export SSH_CLIENT=1` after entering the container (but must be before loading `liquidprompt`). Or add that line to a `.bashrc` or similar.
3. Set [LP_HOSTNAME_ALWAYS](https://liquidprompt.readthedocs.io/en/stable/config.html#LP_HOSTNAME_ALWAYS) to `1`. This will force the hostname to always be displayed. If you only want that behavior inside the container, you could add some logic in your config to only set that if it detects being inside the container.

I realize this probably is not the answer you were looking for. If I am wrong, and there is a way to detect an SSH connection inside a container without using environment variables, please let me know and we can reopen this and reevaluate if it is possible to implement that in Liquid Prompt.
