### ISSUE TITLE
Config options LP_COLOR_OS_* are missing

### ISSUE THREAD

**Issue by tkapias** [liquidprompt/liquidprompt#809]
Shell: Bash 5.2.15(1)-release
Operating system: Debian GNU/Linux trixie/sid - Linux Debian 6.5.10-1 (2023-11-03) x86_64 GNU/Linux
Liquid Prompt version: v2.2.0-rc.2

### Steps to Reproduce

1. source a file with these options:

``` bash
LP_ENABLE_OS=1
LP_ENABLE_OS_ARCH=0
LP_ENABLE_OS_DISTRIB=1
LP_ENABLE_OS_FAMILY=0
LP_ENABLE_OS_KERNEL=0
LP_ENABLE_OS_VERSION=1
LP_COLOR_OS_ARCH=$BLUE
LP_COLOR_OS_DISTRIB=$BLUE
LP_COLOR_OS_FAMILY=$BLUE
LP_COLOR_OS_KERNEL=$BLUE
LP_COLOR_OS_VERSION=$BLUE
```
Do not declare `LP_MARK_OS` which would just assign a white color to all of them.

2. Source the liquidprompt script

### Expected Behavior

Informations about the OS should be displayed in blue color in the prompt.

### Current Behavior

Informations about the OS are displayed in generated colors.

### Possible Cause/Solution

The color variables are everywhere in the docs and the contribs but running a grep on the script shows that they do not exist. I believe that it was not implemented in the ùaster, or the implementation was reversed.

**Comment by Rycieos** [comment]
Add some line like `printf '%q\n' "$BLUE"` in your config file that you source. You will see that `$BLUE` is an unset/empty variable. This is because Liquid Prompt only sets `$BLUE` and other color variables right before loading a config file. Variable names like `BLUE` are too generic to assume no user or other script would ever set them, so we try not to stomp on them. But we want the short names to make writing config files easy. I do not see us ever changing how that works, but I am open to ideas.

That said, I do have solutions for your issue. I see two things you might be trying to do:
1. Loading a file with config options as part of shell startup. Either in a `.bashrc` or similar, or a file sourced from such a file.
  If this is the case, put the options inside of a Liquid Prompt config file instead. Then such variables will work correctly.
2. Loading a file with config options as a way to test various Liquid Prompt configurations. While this does work for static config options, trying to set anything to a variable like this does not. But there are options.
a. Use `lp_terminal_format()` instead of `$BLUE`. It is more verbose though.
b. Similar to (a), make your own `$BLUE` with `lp_terminal_format`: `lp_terminal_format 4 && BLUE=$lp_terminal_format`. This can be done on the fly, or in your `.bashrc` or similar after loading Liquid Prompt.
c. Add those lines temporarily to your config file, then reload it with `lp_activate`.
d. Similar to (c), have an extra config file that you source from the main one, that works as a scratch space that is normally empty, but you can fill when testing things.

Let me know if you still have questions.
