### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by xuanruiqi** [liquidprompt/liquidprompt#828]
Hey! It has been quite a while since this last saw a release, but I see that quite a few fixes were merged since then. Would you mind making a new, minor release? (i.e. 2.1.3). Thanks a lot!

**Comment by Rycieos** [comment]
I was thinking that there haven't been that many fixes, but I found 18 commits with fixes that I would backport to a patch release. So I guess I will do a v2.1.3, since v2.2.0 has been stuck for a while now.

**Comment by xuanruiqi** [comment]
Hm, allow me to slightly derail the discussion, but what is still missing in 2.2.0? The latest RC looks pretty close to a new release?

**Comment by Rycieos** [comment]
You make a fair point, it might be easier to finish up 2.2.0 than to split work to a 2.1.3.

The milestone is tracking things still missing: https://github.com/liquidprompt/liquidprompt/milestone/8

3 of the remaining issues (one of which is duplicated by this issue) can be done after the release.

The other, #827, should be wrapped up very soon.

The true blocker has been the Powerline theme, which has been split into a different repo (which is why it does not show up in the milestone).

You can see the progress in liquidprompt/liquidprompt-powerline#1 and liquidprompt/liquidprompt-powerline#2. Those have stalled out because @nojhan was driving them and he has been busy elsewhere.

The original plan was to split the Powerline themes into a different repo (done) and remove them from this repo. But the more I think about it, I don't want to completely remove them from this repo and risk breaking anything. I think all that remains is to make some docs changes to document the deprecation and redirect interest to the new repo. I'll open a tracking PR for that now.

I think blocking v2.2.0 on that other repo is no longer the right call, so I will work to drive a v2.2.0 release this week.

I will close this issue: let's consolidate discussion about v2.2.0 release in #808. If you still want to argue for a v2.1.3, you can reopen this issue.

**Comment by xuanruiqi** [comment]
No - I completely agree that a prompt 2.2.0 release would obliviate the need for a 2.1.3. And the focus should definitely be on new releases.
