### ISSUE TITLE
Docs mention example config but it was removed 2 years ago

### ISSUE THREAD

**Issue by rpatterson** [liquidprompt/liquidprompt#832]
[The docs mention a `~/liquidprompt/liquidpromptrc-dist` file](https://liquidprompt.readthedocs.io/en/stable/config.html#config-options) but [it was deleted 2 years ago](https://github.com/liquidprompt/liquidprompt/commit/e48ee784bf397a8c98b936ff1b17fd46e5252c13#diff-e41f0b123849c0face4be4896b884ac43995e12dbaeb0319f5a4c64f22641227). Either the docs should be updated or the example file should be restored and updated.

Shell:
```
$ echo $BASH_VERSION
5.2.21(1)-release
```

Operating system:
```
$ uname -a
CYGWIN_NT-10.0-26120 MEDIA 3.5.3-1.x86_64 2024-04-03 17:25 UTC x86_64 Cygwin
$ cat /proc/version
CYGWIN_NT-10.0-26120 version 3.5.3-1.x86_64 (runneradmin@fv-az586-418) (gcc version 11.4.0 (GCC) ) 2024-04-03 17:25 UTC
```
Liquid Prompt version:
```
$ git rev-parse HEAD
2676c18d00b42611db23ac77d97c3f15731b84c3
```

### Steps to Reproduce

1. Note [the directions in the docs](https://liquidprompt.readthedocs.io/en/stable/config.html#config-options) to `$ cp ~/liquidprompt/liquidpromptrc-dist ~/.config/liquidpromptrc`.
2. Note that [the file](https://github.com/liquidprompt/liquidprompt/blob/master/liquidpromptrc-dist) doesn't currently exist.

### Expected Behavior

A user should be able to follow the docs without error.

### Current Behavior

```
$ cp ./liquidpromptrc-dist ~/.config/liquidpromptrc
cp: cannot stat './liquidpromptrc-dist': No such file or directory
```

### Possible Solution

Personally, I prefer having such a file containing all possible configuration options. For example, in my case, I wanted to copy and paste all options to make it easier to disable each `LP_ENABLE_*` option in turn to try and identify what is so slow under Cygwin. I imagine there are many other such use cases, so I recommend restoring and updating the file. It may have even been deleted unintentionally as I can't tell from that commit message why it included removal of that file.

**Comment by rpatterson** [comment]
I'd submit a PR, but I'm not qualified to update it.

**Comment by Rycieos** [comment]
This is a case of version mismatch. You are looking at the "stable" docs (the default), which corresponds with the `stable` branch, which is currently at v2.1.2. The commit you linked is on the `master` branch, and first appeared in [v2.2.0-rc.1](https://github.com/liquidprompt/liquidprompt/releases/tag/v2.2.0-rc.1).

If you look at [the "latest" docs](https://liquidprompt.readthedocs.io/en/latest/config.html) or [the docs specifically for the latest prerelease](https://liquidprompt.readthedocs.io/en/v2.2.0-rc.2/config.html) (v2.2.0-rc.2), they correctly mention the correct method for making a new config file.

Admittedly, the commit message is lacking the reasoning for the removal. But the PR that is the source of that commit (#772) does include such a reason. The script, which replaced the old template file, came about because the template config file kept drifting from the actual defaults.

Anyway, this wouldn't have happened at all if I would just release v2.2.0 finally, so I'll make that a goal for tomorrow.

**Comment by rpatterson** [comment]
> This is a case of version mismatch.

Ah, thanks for clarifying!
