### ISSUE TITLE
install from package manager vs repo

### ISSUE THREAD

**Issue by CouldBeThis** [liquidprompt/liquidprompt#842]
Hi, I installed the `liquidprompt` from the AUR. 

The instructions provided on the Installation page assume the user has cloned repo to their home dir. I don't know how many different permutations there could be but this alternative worked for me:

```sh
[[ $- = *i* ]] && source liquidprompt
```

However for generating a default config I got stuck. Because I don't have the git repo I am not sure where to find this:

> To get your own configuration, you may want to generate a default configuration
> by calling the following script::
> 
>     ./tools/config-from-doc.sh > my_liquidpromptrc

https://github.com/liquidprompt/liquidprompt/blob/786e8c9e02e2c617381a609e7b2eccfb9446131f/docs/config.rst?plain=1#L32

I checked the default config locations mentioned but none of them exist. 

Maybe a simple (?) way to solve this without having to document on the website every possible system set up would be to have a command in the application (like `liquidprompt --help` etc) to spit out the details on the system, like file paths, correct line to source etc, how to run these files, and a link back to the docs in case someone finds it on their own. That assumes you are able to run a binary of course.

Can't imagine I'm the first person to come up with this idea. Just mentioning in case the very very beginners get forgotten.

**Comment by Rycieos** [comment]
Thanks for bringing this up.

Checking [the PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=liquidprompt), it contains:

```bash
build () {
  cd "${pkgname}-${_pkgver//_/-}"
  ./tools/config-from-doc.sh > liquidpromptrc-dist
}

package() {
  cd "${pkgname}-${_pkgver//_/-}"
  install -Dm755 liquidprompt "${pkgdir}/usr/bin/liquidprompt"
  install -Dm644 liquidpromptrc-dist "${pkgdir}/etc/liquidpromptrc"
  ...
```

So it looks like you should have an RC in `/etc/liquidpromptrc`. Could you confirm if that is the case?

Even if that is the case, you are right in that the docs are confusing here.

> Maybe a simple (?) way to solve this without having to document on the website every possible system set up would be to have a command in the application (like `liquidprompt --help` etc) to spit out the details on the system, like file paths, correct line to source etc, how to run these files, and a link back to the docs in case someone finds it on their own. That assumes you are able to run a binary of course.

That is an interesting suggestion. Currently, `liquidprompt` is only meant to be sourced, not executed. In fact, if you execute it as a script in Bash, it prints 
> ./liquidprompt: line 30: return: can only `return' from a function or sourced script

And in Zsh it does nothing at all.

I think changing that to printing some basic help message would be a great idea.

So I see these possible improvements:
- [ ] Add to [the release script](https://github.com/liquidprompt/liquidprompt/blob/master/.github/workflows/release.yml) a step to run the `./tools/config-from-doc.sh` script an include a `liquidpromptrc-dist` in the release tarball. That would save packagers from needing to do that, and anyone who downloads the release tarball.
- [ ] Improve the docs around the config file to suggest that the release tarball or the installed package might have come with an example config file.
- [ ] Catch if `liquidprompt` is executed, and print a help message and exit. The help message should likely contain instructions for sourcing instead of executing, links to the documentation, a list of user facing functions, and basics on config files.

**Comment by CouldBeThis** [comment]
> So it looks like you should have an RC in `/etc/liquidpromptrc`. Could you confirm if that is the case?

Oh you know what, you are correct. I do have it. I guess I missed it when I looked. I apologize for inaccurate report. 

> > ./liquidprompt: line 30: return: can only `return' from a function or sourced script
> 
> And in Zsh it does nothing at all.

I get that printout regardless of whether I try to run from bash or zsh. Which is good because at least it gives some clue about what's going on. If it would just fail silently I  might have just thought it was non-functional or something. 

thanks for taking the time to consider my request.

**Comment by Rycieos** [comment]
(I do my best documentation work on Saturdays, much to the disappointment of my employer.)

I added a handful of commits that should resolve my above checklist.

I added this to the v2.3 milestone, as I don't think it fits as a fix, so shouldn't go in a patch version.

Let me know if there are any improvements that could be made to my solution.
