### ISSUE TITLE
number the lines in PS2

### ISSUE THREAD

**Issue by ardrabczyk** [liquidprompt/liquidprompt#843]
### Description

Would the maintainer be interested in changing the behavior of PS2 prompt? It could for example number the lines as the minimal example ps2.sh like that:

    #!/usr/bin/env bash

    reset_lines() {
        line=0
        echo $line > /tmp/LINE
    }

    number_lines_activate() {
        line=$(< /tmp/LINE)
        line=$((line+1))
        echo $line | tee /tmp/LINE
    }

    PROMPT_COMMAND=reset_lines
    PS2="\e[4;37m\$(number_lines_activate)\e[0m     "

### Example prompt

    $ bash --norc --noprofile
    bash-5.2$ . ps2.sh
    bash-5.2$ a='a
    1     very
    2     long
    3     multiline'
    bash-5.2$ b='another
    1     very
    2     very
    3     veeeery
    4     long
    5     multiline'

**Comment by Rycieos** [comment]
I took a while to respond because I wanted to give this a fair chance by giving it plenty of thought. But I think this is outside of scope for Liquid Prompt.

Writing temp data to a file like this is less than ideal. But it is the only way to do it, because `PS2` (and other `PS` vars) are executed in a subshell, and so variables do not carry over. But that is besides the point.

The truth is I don't see the benefit of Liquid Prompt managing this. We currently have no other data that would make sense in `PS2`, which is why we currently do not manage it. Packaging this into a data function, then asking themes to implement generating PS2 as well (which would likely mean a new function for themes to implement, maybe `_lp_<theme>_set_ps2()`) sounds like a losing battle. I don't think it would be worth it.

On top of that, I don't see why you can't simply stick those lines in your `.bashrc`. Nothing Liquid Prompt does would conflict with that, as long as you run those lines before you load Liquid Prompt. I tested that myself and it works great.

Again, I don't like rejecting features, but I do not think this is in scope. Feel free to convince me otherwise.

For what it's worth, I would rewrite it like this:
```bash
__PROMPT_PS2_LINE_FILE="$(mktemp)"  # could also incorporate the PID of the shell in the filename.

reset_lines() {
    rm "$__PROMPT_PS2_LINE_FILE"
}

number_lines_activate() {
    if [[ -r $__PROMPT_PS2_LINE_FILE ]]; then
        line=$(< "$__PROMPT_PS2_LINE_FILE")
    else
        line=0
    fi
    line=$((line+1))
    printf '%s\n' "$line" > "$__PROMPT_PS2_LINE_FILE"
    printf '%s' "$line"
}

PROMPT_COMMAND=reset_lines
PS2="\e[4;37m\$(number_lines_activate)\e[0m > "
```
