### ISSUE TITLE
[Feature] add SHPOOL multiplexer support

### ISSUE THREAD

**Issue by tkapias** [liquidprompt/liquidprompt#848]
### Description
Just like we currently have a feature to display the session name for Tmux or Screen, I would like to see the same feature for a tool called [shpool](https://github.com/shell-pool).

### How will this be useful?
For users with a tiling window manager (ex. i3) or/and a modern terminal emulator (ex. kitty), multiplexers like tmux are redundant. But, when working on ssh sessions persistence is a must have and shpool is one of the best solutions.

shpool has an internal feature to inject the current session name in the prompt, but it interacts badly with Liquid Prompt and prints some errors. At least the feature [can be disabled](https://github.com/shell-pool/shpool/blob/master/CONFIG.md#prompt-prefix) in shpool's config file to let Liquid Prompt take over.

### Example prompt
Same as the current Tmux/Screen session feature.
Shpool offers an env variable containing the session name : `$SHPOOL_SESSION_NAME`

**Comment by Rycieos** [comment]
> For users with a tiling window manager (ex. i3) or/and a modern terminal emulator (ex. kitty), multiplexers like tmux are redundant. But, when working on ssh sessions persistence is a must have and shpool is one of the best solutions.

Thanks for sharing this tool. It looks very slick; exactly what I want out of a session manager. I'll for sure be giving this a try in my workflows.
 
> shpool has an internal feature to inject the current session name in the prompt, but it interacts badly with Liquid Prompt and prints some errors. At least the feature [can be disabled](https://github.com/shell-pool/shpool/blob/master/CONFIG.md#prompt-prefix) in shpool's config file to let Liquid Prompt take over.

You were not kidding, it is very broken. [It appears to make many mistakes when manipulating `PROMPT_COMMAND`](https://github.com/shell-pool/shpool/blob/0b4ee402f549e823c23601cb802de2a0f7bbdb0e/libshpool/src/daemon/prompt.rs#L64-L78). Maybe if I like the tool I will make a PR to resolve those issues.

> Just like we currently have a feature to display the session name for Tmux or Screen, I would like to see the same feature for a tool called shpool.
> 
> Same as the current Tmux/Screen session feature.
> Shpool offers an env variable containing the session name : `$SHPOOL_SESSION_NAME`

It sounds like you are asking for the name of the shpool session to be in the prompt somewhere. Currently neither screen nor tmux do that, but there is a related feature request for it in #726, though technically that feature request is to show a count of how many sessions are named (excluding ones with default names).

Since that functionality currently does not exist, I will focus on the other part of this issue: feature parity with screen and tmux. That is very easy to do, and I have already done it.

If you want the name of the session you are running in as part of the prompt, I think that is a valid feature request. Please open a separate issue for that.
